language: go
go: 
 - release

before_install:
  - go get github.com/mattn/goveralls

script:
 - go test -v ./...
 - go test -covermode=count -coverprofile=profile.cov
 - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci